### ISSUE TITLE
Auto Rejudge

### ISSUE THREAD

**Issue by sschaub** [bjucps/open-contest#5]
Add a "Rejudge All" button to each problem listed in the /problems view of the Admin user. When clicked, the system should rejudge all submissions of that problem.

The rejudging process should work as follows:
```
let ctime = current time. 
for each contestant:
  for each of the contestant's submissions with timestamp < ctime:
    if the submission's result != "reject":
       rejudge the submission
```

**Comment by zrev2220** [comment]
Should the button be _inside_ each problem card or _outside_ (i.e. below or to the side)? If I put the button on the inside, it's not clickable because the entire card is a link to the problem--clicking the button takes me to the problem instead of triggering the button.

**Comment by zrev2220** [comment]
Also, should `ctime` be determined by the client or the server? If the client sets it, there could be slight inaccuracies due to computers' clocks being inexact. If the server sets it, there could be a delay between when the rejudge was requested and when the server receives the directive due to network speeds and delays.

**Comment by sschaub** [comment]
> Should the button be _inside_ each problem card or _outside_

Feel free to put it wherever makes sense to you.

> Also, should `ctime` be determined by the client or the server?

The server.
