### ISSUE TITLE
Judge Review Queue

### ISSUE THREAD

**Issue by sschaub** [bjucps/open-contest#9]
Add two new attributes Submission: “submission status” and "checkout".
* "Submission status" can have one of two values: “review” or “judged”. 
* "Checkout" has the ID of a judge that is currently reviewing the submission.

Add two new columns to the /judge view that display these attribute values. By default, the filter should display only records with the value "review."

When a contestant submits an attempt, if the system determines that the result is correct, TLE, or runtime crash, the status should be set to “judged.” 

If the system determines that the result is wrong answer, incomplete output, or extra output, the status should be set to “review,” and the contestant sees “pending” as the result.

When a judge selects a submission from the list, the system records the judge's id in the submission's "checkout" attribute and displays the submission details popup. The judge reviews the submission and modifies the result, if desired, then changes the status to "judged." 

When one judge has a submission open to review and another judge attempts to open the same submission, the system should display a dialog to the second judge indicating which judge has the submission open for review and asking if the judge wishes to override. 

To handle multiuser conflicts, add a version number attribute to the submission and increment / check it using the techniques discussed in class.

**Comment by zrev2220** [comment]
When another judge attempts to review a submission already being reviewed by someone, and the judge decides to override, should this judge "steal" the `checkout` value of the submission from the first judge?

One scenario I foresee with this approach: Judge A opens a submission, `checkout=A`. Judge B then opens the submission and chooses to override, `checkout=B`. But then B finishes reviewing, closes the window, and checkout is cleared, `checkout=None`. But A still has his window open. If Judge C comes along and opens the submission, he will do so with no contest since checkout is not held by any judge at the time.

Despite this scenario, I still feel like "stealing" the checkout value is the most reasonable approach.

**Comment by sschaub** [comment]
> should this judge "steal" the `checkout` value of the submission from the first judge?

Yes. In the scenario you describe, when B overrides and steals the submission from A, A should not "regain" the submission when B closes the window. A has permanently lost it. If A attempts to make any change, the application should detect that A has lost the submission and notify A that another user has changed the record.
